export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const TRY_CREATE_USER = "TRY_CREATE_USER";
export const AJOUT_FAIL = 'AJOUT_FAIL';
export const TRY_DELETE_USER = "TRY_DELETE_USER";

export const GET_LIST_PATIENTS = 'GET_LIST_PATIENTS';
export const GET_LIST_DOSSIER = 'GET_LIST_DOSSIER';
export const GET_LIST_RENDEZVOUS = 'GET_LIST_RENDEZVOUS';
export const GET_LIST_ACTUALITE = 'GET_LIST_ACTUALITE';

export const TRY_UPDATE_USER = "TRY_UPDATE_USER";
export const TRY_UPDATE_RENDEZVOUS = "TRY_UPDATE_RENDEZVOUS";
export const TRY_UPDATE_DOSSIERMEDICAL = "TRY_UPDATE_DOSSIERMEDICAL";
export const TRY_UPDATE_ACTUALITE = "TRY_UPDATE_ACTUALITE";

export const COUNT_RENDEZVOUS = 'COUNT_RENDEZVOUS';

